# Generated by Django 5.1.3 on 2025-11-03 13:49

import django.db.models.deletion
import guests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0017_auto_20220807_2143"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={
                "ordering": ["first_name"],
                "verbose_name": "Convidado",
                "verbose_name_plural": "Convidados",
            },
        ),
        migrations.AlterModelOptions(
            name="party",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Grupo/Família",
                "verbose_name_plural": "Grupos/Famílias",
            },
        ),
        migrations.RemoveField(
            model_name="guest",
            name="meal",
        ),
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="first_name",
            field=models.CharField(max_length=60, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="guest",
            name="is_attending",
            field=models.BooleanField(
                default=None, null=True, verbose_name="Vai comparecer?"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="is_child",
            field=models.BooleanField(default=False, verbose_name="É criança?"),
        ),
        migrations.AlterField(
            model_name="guest",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Sobrenome"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="guests.party",
                verbose_name="Grupo/Família",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="category",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Categoria"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Comentários"),
        ),
        migrations.AlterField(
            model_name="party",
            name="invitation_id",
            field=models.CharField(
                db_index=True,
                default=guests.models._random_uuid,
                max_length=32,
                unique=True,
                verbose_name="Código do convite",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="invitation_opened",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Convite aberto"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="invitation_sent",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Convite enviado"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="is_attending",
            field=models.BooleanField(
                default=None, null=True, verbose_name="Vai comparecer?"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="is_invited",
            field=models.BooleanField(default=False, verbose_name="Convite enviado?"),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Nome do grupo ou família"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="rehearsal_dinner",
            field=models.BooleanField(default=False, verbose_name="Jantar de ensaio"),
        ),
        migrations.AlterField(
            model_name="party",
            name="save_the_date_opened",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Save the date aberto"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="save_the_date_sent",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Save the date enviado",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="type",
            field=models.CharField(
                choices=[
                    ("formal", "Formal"),
                    ("fun", "Divertido"),
                    ("dimagi", "Dimagi"),
                ],
                max_length=10,
                verbose_name="Tipo de convite",
            ),
        ),
    ]
