# Generated by Django 5.1.3 on 2025-11-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0018_alter_guest_options_alter_party_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="email",
        ),
        migrations.AddField(
            model_name="guest",
            name="contact",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Contato (WhatsApp)"
            ),
        ),
    ]
