# Generated by Django 5.1.3 on 2025-11-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0019_remove_guest_email_guest_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteAccessLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data/Hora do acesso"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="Navegador / Dispositivo"
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guests.party",
                        verbose_name="Grupo/Família",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Acesso",
                "verbose_name_plural": "Rastreabilidade de Convites",
                "ordering": ["-accessed_at"],
            },
        ),
    ]
